import { Template } from '@/types';

// Szablony banerów - główne narzędzie promocyjne dla drukarni
export const bannerTemplates: Template[] = [
  // ROLL-UP FIRMOWE
  {
    id: 'baner-rollup-1',
    name: 'Roll-up Firmowy - Niebieski',
    productId: 'baner-100x200',
    category: 'banery',
    thumbnail: '/templates/baner-rollup-1.png',
    tags: ['firmowy', 'roll-up', 'biznes'],
    data: JSON.stringify({
      version: '5.3.0',
      objects: [
        { type: 'rect', left: 0, top: 0, width: 11811, height: 23622, fill: '#3498db' },
        { type: 'rect', left: 0, top: 10000, width: 11811, height: 3622, fill: '#2980b9' },
        { type: 'text', left: 5905, top: 8000, text: 'TWOJA FIRMA', fontFamily: 'Arial', fontSize: 480, fill: '#ffffff', fontWeight: 'bold', textAlign: 'center' },
        { type: 'text', left: 5905, top: 11000, text: 'Profesjonalne rozwiązania IT', fontFamily: 'Arial', fontSize: 280, fill: '#ffffff', textAlign: 'center' },
        { type: 'text', left: 5905, top: 16000, text: '✓ Najwyższa jakość', fontFamily: 'Arial', fontSize: 220, fill: '#ffffff', textAlign: 'center' },
        { type: 'text', left: 5905, top: 16600, text: '✓ Doświadczenie', fontFamily: 'Arial', fontSize: 220, fill: '#ffffff', textAlign: 'center' },
        { type: 'text', left: 5905, top: 17200, text: '✓ Konkurencyjne ceny', fontFamily: 'Arial', fontSize: 220, fill: '#ffffff', textAlign: 'center' },
        { type: 'text', left: 5905, top: 20000, text: 'www.firma.pl  •  +48 123 456 789', fontFamily: 'Arial', fontSize: 200, fill: '#ffffff', textAlign: 'center', fontWeight: 'bold' },
      ],
    }),
  },
  {
    id: 'baner-rollup-2',
    name: 'Roll-up Produktowy - Promocja',
    productId: 'baner-100x200',
    category: 'banery',
    thumbnail: '/templates/baner-rollup-2.png',
    tags: ['produktowy', 'roll-up', 'oferta', 'promocja'],
    data: JSON.stringify({
      version: '5.3.0',
      objects: [
        { type: 'rect', left: 0, top: 0, width: 11811, height: 23622, fill: '#ffffff' },
        { type: 'rect', left: 0, top: 0, width: 11811, height: 3000, fill: '#27ae60' },
        { type: 'rect', left: 0, top: 20622, width: 11811, height: 3000, fill: '#27ae60' },
        { type: 'text', left: 5905, top: 800, text: 'NOWA OFERTA', fontFamily: 'Arial', fontSize: 420, fill: '#ffffff', fontWeight: 'bold', textAlign: 'center' },
        { type: 'text', left: 5905, top: 6000, text: 'PROMOCJA', fontFamily: 'Arial', fontSize: 520, fill: '#27ae60', fontWeight: 'bold', textAlign: 'center' },
        { type: 'text', left: 5905, top: 8000, text: '-30%', fontFamily: 'Arial', fontSize: 800, fill: '#e74c3c', fontWeight: 'bold', textAlign: 'center' },
        { type: 'text', left: 5905, top: 10500, text: 'NA WSZYSTKIE PRODUKTY', fontFamily: 'Arial', fontSize: 320, fill: '#2c3e50', textAlign: 'center' },
        { type: 'text', left: 5905, top: 15000, text: 'Tylko do końca miesiąca!', fontFamily: 'Arial', fontSize: 280, fill: '#7f8c8d', textAlign: 'center' },
        { type: 'text', left: 5905, top: 21500, text: 'WWW.SKLEP.PL', fontFamily: 'Arial', fontSize: 360, fill: '#ffffff', textAlign: 'center', fontWeight: 'bold' },
      ],
    }),
  },
  {
    id: 'baner-rollup-3',
    name: 'Roll-up Medyczny',
    productId: 'baner-100x200',
    category: 'banery',
    thumbnail: '/templates/baner-rollup-3.png',
    tags: ['medyczny', 'roll-up', 'zdrowie'],
    data: JSON.stringify({
      version: '5.3.0',
      objects: [
        { type: 'rect', left: 0, top: 0, width: 11811, height: 23622, fill: '#ffffff' },
        { type: 'rect', left: 0, top: 0, width: 1500, height: 23622, fill: '#27ae60' },
        { type: 'text', left: 7000, top: 5000, text: 'PRZYCHODNIA', fontFamily: 'Arial', fontSize: 520, fill: '#27ae60', fontWeight: 'bold' },
        { type: 'text', left: 7000, top: 6000, text: 'ZDROWIE', fontFamily: 'Arial', fontSize: 420, fill: '#2c3e50', fontWeight: 'bold' },
        { type: 'text', left: 7000, top: 9000, text: 'Profesjonalna opieka medyczna', fontFamily: 'Arial', fontSize: 260, fill: '#7f8c8d' },
        { type: 'text', left: 7000, top: 12000, text: '✓ Lekarze specjaliści', fontFamily: 'Arial', fontSize: 220, fill: '#2c3e50' },
        { type: 'text', left: 7000, top: 12700, text: '✓ Nowoczesny sprzęt', fontFamily: 'Arial', fontSize: 220, fill: '#2c3e50' },
        { type: 'text', left: 7000, top: 13400, text: '✓ Bez kolejek', fontFamily: 'Arial', fontSize: 220, fill: '#2c3e50' },
        { type: 'text', left: 7000, top: 14100, text: '✓ Parking gratis', fontFamily: 'Arial', fontSize: 220, fill: '#2c3e50' },
        { type: 'text', left: 7000, top: 19000, text: 'Rejestracja: +48 123 456 789', fontFamily: 'Arial', fontSize: 280, fill: '#27ae60', fontWeight: 'bold' },
      ],
    }),
  },
  {
    id: 'baner-rollup-4',
    name: 'Roll-up Fitness - Siłownia',
    productId: 'baner-100x200',
    category: 'banery',
    thumbnail: '/templates/baner-rollup-4.png',
    tags: ['fitness', 'roll-up', 'sport'],
    data: JSON.stringify({
      version: '5.3.0',
      objects: [
        { type: 'rect', left: 0, top: 0, width: 11811, height: 23622, fill: '#1a1a1a' },
        { type: 'rect', left: 0, top: 20000, width: 11811, height: 3622, fill: '#e74c3c' },
        { type: 'text', left: 5905, top: 6000, text: 'FITNESS', fontFamily: 'Arial', fontSize: 680, fill: '#e74c3c', fontWeight: 'bold', textAlign: 'center' },
        { type: 'text', left: 5905, top: 7500, text: 'CLUB', fontFamily: 'Arial', fontSize: 580, fill: '#ffffff', fontWeight: 'bold', textAlign: 'center' },
        { type: 'text', left: 5905, top: 10000, text: 'PIERWSZE 2 TYGODNIE GRATIS', fontFamily: 'Arial', fontSize: 340, fill: '#e74c3c', textAlign: 'center', fontWeight: 'bold' },
        { type: 'text', left: 5905, top: 13000, text: '💪 Nowoczesny sprzęt', fontFamily: 'Arial', fontSize: 240, fill: '#ffffff', textAlign: 'center' },
        { type: 'text', left: 5905, top: 13800, text: '💪 Trenerzy personalni', fontFamily: 'Arial', fontSize: 240, fill: '#ffffff', textAlign: 'center' },
        { type: 'text', left: 5905, top: 14600, text: '💪 Zajęcia grupowe', fontFamily: 'Arial', fontSize: 240, fill: '#ffffff', textAlign: 'center' },
        { type: 'text', left: 5905, top: 15400, text: '💪 Sauna i jacuzzi', fontFamily: 'Arial', fontSize: 240, fill: '#ffffff', textAlign: 'center' },
        { type: 'text', left: 5905, top: 20800, text: 'ZAPISZ SIĘ: +48 123 456 789', fontFamily: 'Arial', fontSize: 320, fill: '#ffffff', textAlign: 'center', fontWeight: 'bold' },
      ],
    }),
  },
  {
    id: 'baner-rollup-5',
    name: 'Roll-up Salon Urody',
    productId: 'baner-100x200',
    category: 'banery',
    thumbnail: '/templates/baner-rollup-5.png',
    tags: ['uroda', 'roll-up', 'fryzjer', 'salon'],
    data: JSON.stringify({
      version: '5.3.0',
      objects: [
        { type: 'rect', left: 0, top: 0, width: 11811, height: 23622, fill: '#fce4ec' },
        { type: 'text', left: 5905, top: 4000, text: 'SALON URODY', fontFamily: 'Georgia', fontSize: 620, fill: '#e91e63', fontWeight: 'bold', textAlign: 'center' },
        { type: 'text', left: 5905, top: 5500, text: 'Metamorfoza', fontFamily: 'Georgia', fontSize: 480, fill: '#880e4f', textAlign: 'center' },
        { type: 'text', left: 5905, top: 9000, text: 'Fryzjerstwo', fontFamily: 'Arial', fontSize: 340, fill: '#c2185b', textAlign: 'center', fontWeight: 'bold' },
        { type: 'text', left: 5905, top: 10000, text: 'Manicure & Pedicure', fontFamily: 'Arial', fontSize: 340, fill: '#c2185b', textAlign: 'center', fontWeight: 'bold' },
        { type: 'text', left: 5905, top: 11000, text: 'Makijaż Permanentny', fontFamily: 'Arial', fontSize: 340, fill: '#c2185b', textAlign: 'center', fontWeight: 'bold' },
        { type: 'text', left: 5905, top: 12000, text: 'Stylizacja Brwi', fontFamily: 'Arial', fontSize: 340, fill: '#c2185b', textAlign: 'center', fontWeight: 'bold' },
        { type: 'text', left: 5905, top: 16000, text: '-20% NA PIERWSZE WIZYTY', fontFamily: 'Arial', fontSize: 380, fill: '#e74c3c', textAlign: 'center', fontWeight: 'bold' },
        { type: 'text', left: 5905, top: 19500, text: 'Umów wizytę: +48 123 456 789', fontFamily: 'Arial', fontSize: 280, fill: '#880e4f', textAlign: 'center' },
      ],
    }),
  },
  {
    id: 'baner-rollup-6',
    name: 'Roll-up Auto Serwis',
    productId: 'baner-100x200',
    category: 'banery',
    thumbnail: '/templates/baner-rollup-6.png',
    tags: ['auto', 'roll-up', 'mechanik', 'serwis'],
    data: JSON.stringify({
      version: '5.3.0',
      objects: [
        { type: 'rect', left: 0, top: 0, width: 11811, height: 23622, fill: '#2c2c2c' },
        { type: 'rect', left: 0, top: 0, width: 11811, height: 500, fill: '#f39c12' },
        { type: 'rect', left: 0, top: 23122, width: 11811, height: 500, fill: '#f39c12' },
        { type: 'text', left: 5905, top: 5000, text: 'AUTO SERWIS', fontFamily: 'Arial', fontSize: 680, fill: '#f39c12', fontWeight: 'bold', textAlign: 'center' },
        { type: 'text', left: 5905, top: 6800, text: 'Profesjonalna Naprawa', fontFamily: 'Arial', fontSize: 380, fill: '#ffffff', textAlign: 'center' },
        { type: 'text', left: 5905, top: 10000, text: '🔧 Mechanika pojazdowa', fontFamily: 'Arial', fontSize: 280, fill: '#ecf0f1', textAlign: 'center' },
        { type: 'text', left: 5905, top: 10900, text: '🔧 Wymiana opon', fontFamily: 'Arial', fontSize: 280, fill: '#ecf0f1', textAlign: 'center' },
        { type: 'text', left: 5905, top: 11800, text: '🔧 Klimatyzacja', fontFamily: 'Arial', fontSize: 280, fill: '#ecf0f1', textAlign: 'center' },
        { type: 'text', left: 5905, top: 12700, text: '🔧 Diagnostyka komputerowa', fontFamily: 'Arial', fontSize: 280, fill: '#ecf0f1', textAlign: 'center' },
        { type: 'text', left: 5905, top: 13600, text: '🔧 Przeglądy okresowe', fontFamily: 'Arial', fontSize: 280, fill: '#ecf0f1', textAlign: 'center' },
        { type: 'text', left: 5905, top: 17000, text: 'RABAT -15% DLA STAŁYCH KLIENTÓW', fontFamily: 'Arial', fontSize: 300, fill: '#f39c12', textAlign: 'center', fontWeight: 'bold' },
        { type: 'text', left: 5905, top: 20000, text: 'Tel: +48 123 456 789', fontFamily: 'Arial', fontSize: 340, fill: '#f39c12', textAlign: 'center', fontWeight: 'bold' },
      ],
    }),
  },

  // BANERY REKLAMOWE
  {
    id: 'baner-reklamowy-1',
    name: 'Baner Reklamowy - Restauracja',
    productId: 'baner-200x100',
    category: 'banery',
    thumbnail: '/templates/baner-reklamowy-1.png',
    tags: ['reklamowy', 'restauracja', 'gastronomia'],
    data: JSON.stringify({
      version: '5.3.0',
      objects: [
        { type: 'rect', left: 0, top: 0, width: 23622, height: 11811, fill: '#c0392b' },
        { type: 'text', left: 11811, top: 3500, text: 'RESTAURACJA "SMAK"', fontFamily: 'Georgia', fontSize: 520, fill: '#ffffff', fontWeight: 'bold', textAlign: 'center' },
        { type: 'text', left: 11811, top: 4500, text: 'Tradycyjna Kuchnia Polska', fontFamily: 'Georgia', fontSize: 320, fill: '#f39c12', textAlign: 'center' },
        { type: 'text', left: 11811, top: 7000, text: 'Otwarte codziennie 12:00 - 22:00', fontFamily: 'Arial', fontSize: 280, fill: '#ffffff', textAlign: 'center' },
        { type: 'text', left: 11811, top: 8000, text: 'ul. Smaczna 1  •  Tel: +48 123 456 789', fontFamily: 'Arial', fontSize: 240, fill: '#ffffff', textAlign: 'center' },
      ],
    }),
  },
  {
    id: 'baner-reklamowy-2',
    name: 'Baner Reklamowy - Sklep',
    productId: 'baner-200x100',
    category: 'banery',
    thumbnail: '/templates/baner-reklamowy-2.png',
    tags: ['reklamowy', 'sklep', 'handel'],
    data: JSON.stringify({
      version: '5.3.0',
      objects: [
        { type: 'rect', left: 0, top: 0, width: 23622, height: 11811, fill: '#ffffff' },
        { type: 'rect', left: 0, top: 0, width: 23622, height: 2000, fill: '#e74c3c' },
        { type: 'rect', left: 0, top: 9811, width: 23622, height: 2000, fill: '#e74c3c' },
        { type: 'text', left: 11811, top: 400, text: 'WIELKA WYPRZEDAŻ', fontFamily: 'Arial', fontSize: 480, fill: '#ffffff', fontWeight: 'bold', textAlign: 'center' },
        { type: 'text', left: 11811, top: 4500, text: '-50%', fontFamily: 'Arial', fontSize: 900, fill: '#e74c3c', fontWeight: 'bold', textAlign: 'center' },
        { type: 'text', left: 11811, top: 10200, text: 'DO 31 GRUDNIA  •  WWW.SKLEP.PL', fontFamily: 'Arial', fontSize: 360, fill: '#ffffff', fontWeight: 'bold', textAlign: 'center' },
      ],
    }),
  },
  {
    id: 'baner-reklamowy-3',
    name: 'Baner Reklamowy - Nieruchomości',
    productId: 'baner-200x100',
    category: 'banery',
    thumbnail: '/templates/baner-reklamowy-3.png',
    tags: ['reklamowy', 'nieruchomości', 'dom'],
    data: JSON.stringify({
      version: '5.3.0',
      objects: [
        { type: 'rect', left: 0, top: 0, width: 23622, height: 11811, fill: '#3498db' },
        { type: 'text', left: 11811, top: 2500, text: 'SPRZEDAŻ  •  WYNAJEM', fontFamily: 'Arial', fontSize: 440, fill: '#ffffff', fontWeight: 'bold', textAlign: 'center' },
        { type: 'text', left: 11811, top: 4000, text: 'NIERUCHOMOŚCI', fontFamily: 'Arial', fontSize: 720, fill: '#ffffff', fontWeight: 'bold', textAlign: 'center' },
        { type: 'text', left: 11811, top: 6500, text: 'Domy  •  Mieszkania  •  Lokale', fontFamily: 'Arial', fontSize: 320, fill: '#ecf0f1', textAlign: 'center' },
        { type: 'text', left: 11811, top: 8500, text: 'Bezpłatna Wycena  •  +48 123 456 789', fontFamily: 'Arial', fontSize: 300, fill: '#ffffff', textAlign: 'center', fontWeight: 'bold' },
      ],
    }),
  },
];
