import { Template } from '@/types';

// Szablony wizytówek
export const businessCardTemplates: Template[] = [
  // BIZNESOWE
  {
    id: 'wiz-biznes-1',
    name: 'Elegancka Czerń',
    productId: 'wiz-85x55',
    category: 'wizytowki',
    thumbnail: '/templates/wiz-biznes-1.png',
    tags: ['biznes', 'elegancki', 'czarny'],
    data: JSON.stringify({
      version: '5.3.0',
      objects: [
        { type: 'rect', left: 0, top: 0, width: 1004, height: 650, fill: '#1a1a2e' },
        { type: 'rect', left: 0, top: 0, width: 15, height: 650, fill: '#f39c12' },
        { type: 'text', left: 50, top: 60, text: 'JAN KOWALSKI', fontFamily: 'Arial', fontSize: 52, fill: '#ffffff', fontWeight: 'bold' },
        { type: 'text', left: 50, top: 130, text: 'Dyrektor Zarządzający', fontFamily: 'Arial', fontSize: 24, fill: '#f39c12' },
        { type: 'text', left: 50, top: 480, text: '+48 123 456 789', fontFamily: 'Arial', fontSize: 20, fill: '#ecf0f1' },
        { type: 'text', left: 50, top: 515, text: 'jan.kowalski@firma.pl', fontFamily: 'Arial', fontSize: 20, fill: '#ecf0f1' },
        { type: 'text', left: 50, top: 550, text: 'www.firma.pl', fontFamily: 'Arial', fontSize: 20, fill: '#ecf0f1' },
      ],
    }),
  },
  {
    id: 'wiz-biznes-2',
    name: 'Profesjonalna Biel',
    productId: 'wiz-85x55',
    category: 'wizytowki',
    thumbnail: '/templates/wiz-biznes-2.png',
    tags: ['biznes', 'minimalistyczny', 'biały'],
    data: JSON.stringify({
      version: '5.3.0',
      objects: [
        { type: 'rect', left: 0, top: 0, width: 1004, height: 650, fill: '#ffffff' },
        { type: 'rect', left: 0, top: 600, width: 1004, height: 50, fill: '#2c3e50' },
        { type: 'text', left: 60, top: 200, text: 'ANNA NOWAK', fontFamily: 'Arial', fontSize: 48, fill: '#2c3e50', fontWeight: 'bold' },
        { type: 'text', left: 60, top: 260, text: 'Architekt', fontFamily: 'Arial', fontSize: 28, fill: '#7f8c8d' },
        { type: 'text', left: 60, top: 380, text: 'T: +48 123 456 789', fontFamily: 'Arial', fontSize: 18, fill: '#2c3e50' },
        { type: 'text', left: 60, top: 410, text: 'E: anna@architektura.pl', fontFamily: 'Arial', fontSize: 18, fill: '#2c3e50' },
      ],
    }),
  },
  {
    id: 'wiz-biznes-3',
    name: 'Niebieski Korporacyjny',
    productId: 'wiz-85x55',
    category: 'wizytowki',
    thumbnail: '/templates/wiz-biznes-3.png',
    tags: ['biznes', 'korporacyjny', 'niebieski'],
    data: JSON.stringify({
      version: '5.3.0',
      objects: [
        { type: 'rect', left: 0, top: 0, width: 1004, height: 650, fill: '#ecf0f1' },
        { type: 'rect', left: 0, top: 0, width: 1004, height: 200, fill: '#3498db' },
        { type: 'text', left: 50, top: 60, text: 'MAREK WIŚNIEWSKI', fontFamily: 'Arial', fontSize: 44, fill: '#ffffff', fontWeight: 'bold' },
        { type: 'text', left: 50, top: 120, text: 'Konsultant Biznesowy', fontFamily: 'Arial', fontSize: 24, fill: '#ffffff' },
        { type: 'text', left: 50, top: 280, text: 'Telefon: +48 123 456 789', fontFamily: 'Arial', fontSize: 20, fill: '#2c3e50' },
        { type: 'text', left: 50, top: 320, text: 'Email: marek@consulting.pl', fontFamily: 'Arial', fontSize: 20, fill: '#2c3e50' },
        { type: 'text', left: 50, top: 360, text: 'Web: www.consulting.pl', fontFamily: 'Arial', fontSize: 20, fill: '#2c3e50' },
      ],
    }),
  },

  // KREATYWNE
  {
    id: 'wiz-kreatywna-1',
    name: 'Gradient Fiolet-Róż',
    productId: 'wiz-85x55',
    category: 'wizytowki',
    thumbnail: '/templates/wiz-kreatywna-1.png',
    tags: ['kreatywny', 'kolorowy', 'gradient'],
    data: JSON.stringify({
      version: '5.3.0',
      objects: [
        { type: 'rect', left: 0, top: 0, width: 1004, height: 650, fill: '#667eea' },
        { type: 'rect', left: 600, top: 0, width: 404, height: 650, fill: '#f093fb', opacity: 0.7 },
        { type: 'text', left: 50, top: 250, text: 'MARIA KOWALCZYK', fontFamily: 'Arial', fontSize: 46, fill: '#ffffff', fontWeight: 'bold' },
        { type: 'text', left: 50, top: 310, text: 'Grafik & Projektant', fontFamily: 'Arial', fontSize: 28, fill: '#ffffff' },
        { type: 'text', left: 50, top: 480, text: '📱 +48 123 456 789', fontFamily: 'Arial', fontSize: 20, fill: '#ffffff' },
        { type: 'text', left: 50, top: 520, text: '✉️ maria@creative.pl', fontFamily: 'Arial', fontSize: 20, fill: '#ffffff' },
      ],
    }),
  },
  {
    id: 'wiz-kreatywna-2',
    name: 'Kolorowe Kształty',
    productId: 'wiz-85x55',
    category: 'wizytowki',
    thumbnail: '/templates/wiz-kreatywna-2.png',
    tags: ['kreatywny', 'kolorowy', 'geometryczny'],
    data: JSON.stringify({
      version: '5.3.0',
      objects: [
        { type: 'rect', left: 0, top: 0, width: 1004, height: 650, fill: '#ffffff' },
        { type: 'circle', left: 700, top: -50, radius: 150, fill: '#e74c3c', opacity: 0.3 },
        { type: 'circle', left: 50, top: 400, radius: 100, fill: '#3498db', opacity: 0.3 },
        { type: 'triangle', left: 800, top: 450, width: 150, height: 150, fill: '#f39c12', opacity: 0.3 },
        { type: 'text', left: 50, top: 180, text: 'PIOTR ZIELIŃSKI', fontFamily: 'Arial', fontSize: 48, fill: '#2c3e50', fontWeight: 'bold' },
        { type: 'text', left: 50, top: 245, text: 'Creative Director', fontFamily: 'Arial', fontSize: 26, fill: '#e74c3c' },
        { type: 'text', left: 50, top: 340, text: '+48 123 456 789', fontFamily: 'Arial', fontSize: 20, fill: '#7f8c8d' },
        { type: 'text', left: 50, top: 375, text: 'piotr@studio.pl', fontFamily: 'Arial', fontSize: 20, fill: '#7f8c8d' },
      ],
    }),
  },
  {
    id: 'wiz-kreatywna-3',
    name: 'Złoty Luksus',
    productId: 'wiz-85x55',
    category: 'wizytowki',
    thumbnail: '/templates/wiz-kreatywna-3.png',
    tags: ['kreatywny', 'luksusowy', 'złoty'],
    data: JSON.stringify({
      version: '5.3.0',
      objects: [
        { type: 'rect', left: 0, top: 0, width: 1004, height: 650, fill: '#2c2c2c' },
        { type: 'rect', left: 0, top: 300, width: 1004, height: 4, fill: '#d4af37' },
        { type: 'text', left: 502, top: 150, text: 'JULIA LEWANDOWSKA', fontFamily: 'Arial', fontSize: 42, fill: '#d4af37', fontWeight: 'bold', textAlign: 'center' },
        { type: 'text', left: 502, top: 210, text: 'CEO & Founder', fontFamily: 'Arial', fontSize: 26, fill: '#ffffff', textAlign: 'center' },
        { type: 'text', left: 502, top: 400, text: '+48 123 456 789  |  julia@luxury.pl', fontFamily: 'Arial', fontSize: 20, fill: '#d4af37', textAlign: 'center' },
      ],
    }),
  },

  // MINIMALISTYCZNE
  {
    id: 'wiz-minimal-1',
    name: 'Czarno-Biały Minimal',
    productId: 'wiz-85x55',
    category: 'wizytowki',
    thumbnail: '/templates/wiz-minimal-1.png',
    tags: ['minimalistyczny', 'czarno-biały', 'prosty'],
    data: JSON.stringify({
      version: '5.3.0',
      objects: [
        { type: 'rect', left: 0, top: 0, width: 1004, height: 650, fill: '#ffffff' },
        { type: 'rect', left: 0, top: 325, width: 1004, height: 2, fill: '#000000' },
        { type: 'text', left: 60, top: 250, text: 'TOMASZ KRÓL', fontFamily: 'Arial', fontSize: 42, fill: '#000000', fontWeight: 'bold' },
        { type: 'text', left: 60, top: 360, text: 'Designer', fontFamily: 'Arial', fontSize: 22, fill: '#000000' },
        { type: 'text', left: 60, top: 500, text: '+48 123 456 789', fontFamily: 'Arial', fontSize: 18, fill: '#000000' },
        { type: 'text', left: 60, top: 530, text: 'tomasz@design.pl', fontFamily: 'Arial', fontSize: 18, fill: '#000000' },
      ],
    }),
  },
  {
    id: 'wiz-minimal-2',
    name: 'Jednolita Biel',
    productId: 'wiz-85x55',
    category: 'wizytowki',
    thumbnail: '/templates/wiz-minimal-2.png',
    tags: ['minimalistyczny', 'biały', 'czysty'],
    data: JSON.stringify({
      version: '5.3.0',
      objects: [
        { type: 'rect', left: 0, top: 0, width: 1004, height: 650, fill: '#fafafa' },
        { type: 'text', left: 60, top: 60, text: 'KATARZYNA', fontFamily: 'Arial', fontSize: 38, fill: '#333333' },
        { type: 'text', left: 60, top: 105, text: 'NOWACKA', fontFamily: 'Arial', fontSize: 38, fill: '#333333', fontWeight: 'bold' },
        { type: 'text', left: 60, top: 180, text: 'Photographer', fontFamily: 'Arial', fontSize: 20, fill: '#999999' },
        { type: 'text', left: 60, top: 550, text: 'k.nowacka@photo.pl  •  +48 123 456 789', fontFamily: 'Arial', fontSize: 16, fill: '#666666' },
      ],
    }),
  },
  {
    id: 'wiz-minimal-3',
    name: 'Typograficzny',
    productId: 'wiz-85x55',
    category: 'wizytowki',
    thumbnail: '/templates/wiz-minimal-3.png',
    tags: ['minimalistyczny', 'typografia', 'prosty'],
    data: JSON.stringify({
      version: '5.3.0',
      objects: [
        { type: 'rect', left: 0, top: 0, width: 1004, height: 650, fill: '#ffffff' },
        { type: 'text', left: 502, top: 200, text: 'ADAM', fontFamily: 'Arial', fontSize: 80, fill: '#000000', fontWeight: 'bold', textAlign: 'center' },
        { type: 'text', left: 502, top: 290, text: 'KOWALSKI', fontFamily: 'Arial', fontSize: 32, fill: '#666666', textAlign: 'center' },
        { type: 'text', left: 502, top: 450, text: '+48 123 456 789', fontFamily: 'Arial', fontSize: 18, fill: '#000000', textAlign: 'center' },
        { type: 'text', left: 502, top: 480, text: 'adam@studio.pl', fontFamily: 'Arial', fontSize: 18, fill: '#000000', textAlign: 'center' },
      ],
    }),
  },

  // BRANŻOWE
  {
    id: 'wiz-tech-1',
    name: 'Tech & IT',
    productId: 'wiz-85x55',
    category: 'wizytowki',
    thumbnail: '/templates/wiz-tech-1.png',
    tags: ['tech', 'IT', 'programista'],
    data: JSON.stringify({
      version: '5.3.0',
      objects: [
        { type: 'rect', left: 0, top: 0, width: 1004, height: 650, fill: '#0a0e27' },
        { type: 'rect', left: 0, top: 0, width: 20, height: 650, fill: '#00ff88' },
        { type: 'text', left: 60, top: 60, text: 'MICHAŁ TECH', fontFamily: 'Courier New', fontSize: 42, fill: '#00ff88', fontWeight: 'bold' },
        { type: 'text', left: 60, top: 120, text: '< Full Stack Developer />', fontFamily: 'Courier New', fontSize: 22, fill: '#ffffff' },
        { type: 'text', left: 60, top: 480, text: '$ michal@dev.pl', fontFamily: 'Courier New', fontSize: 18, fill: '#00ff88' },
        { type: 'text', left: 60, top: 515, text: '$ +48 123 456 789', fontFamily: 'Courier New', fontSize: 18, fill: '#00ff88' },
        { type: 'text', left: 60, top: 550, text: '$ github.com/michaltech', fontFamily: 'Courier New', fontSize: 18, fill: '#00ff88' },
      ],
    }),
  },
  {
    id: 'wiz-med-1',
    name: 'Medyczny - Lekarz',
    productId: 'wiz-85x55',
    category: 'wizytowki',
    thumbnail: '/templates/wiz-med-1.png',
    tags: ['medyczny', 'zdrowie', 'lekarz'],
    data: JSON.stringify({
      version: '5.3.0',
      objects: [
        { type: 'rect', left: 0, top: 0, width: 1004, height: 650, fill: '#ffffff' },
        { type: 'rect', left: 0, top: 0, width: 1004, height: 15, fill: '#27ae60' },
        { type: 'text', left: 60, top: 180, text: 'dr ANNA ZDROWA', fontFamily: 'Arial', fontSize: 44, fill: '#2c3e50', fontWeight: 'bold' },
        { type: 'text', left: 60, top: 240, text: 'Lekarz Rodzinny', fontFamily: 'Arial', fontSize: 26, fill: '#27ae60' },
        { type: 'text', left: 60, top: 400, text: 'Tel: +48 123 456 789', fontFamily: 'Arial', fontSize: 20, fill: '#7f8c8d' },
        { type: 'text', left: 60, top: 435, text: 'Email: dr.anna@przychodnia.pl', fontFamily: 'Arial', fontSize: 20, fill: '#7f8c8d' },
        { type: 'text', left: 60, top: 470, text: 'ul. Zdrowia 1, Warszawa', fontFamily: 'Arial', fontSize: 20, fill: '#7f8c8d' },
      ],
    }),
  },
  {
    id: 'wiz-law-1',
    name: 'Prawniczy - Adwokat',
    productId: 'wiz-85x55',
    category: 'wizytowki',
    thumbnail: '/templates/wiz-law-1.png',
    tags: ['prawniczy', 'kancelaria', 'adwokat'],
    data: JSON.stringify({
      version: '5.3.0',
      objects: [
        { type: 'rect', left: 0, top: 0, width: 1004, height: 650, fill: '#1c2833' },
        { type: 'rect', left: 480, top: 0, width: 6, height: 650, fill: '#c0a062' },
        { type: 'text', left: 60, top: 200, text: 'PIOTR SPRAWIEDLIWY', fontFamily: 'Georgia', fontSize: 38, fill: '#c0a062', fontWeight: 'bold' },
        { type: 'text', left: 60, top: 250, text: 'Radca Prawny', fontFamily: 'Georgia', fontSize: 24, fill: '#ecf0f1' },
        { type: 'text', left: 60, top: 450, text: 'Kancelaria Prawna "Sprawiedliwość"', fontFamily: 'Georgia', fontSize: 18, fill: '#bdc3c7' },
        { type: 'text', left: 60, top: 485, text: 'Tel: +48 123 456 789', fontFamily: 'Georgia', fontSize: 18, fill: '#bdc3c7' },
        { type: 'text', left: 60, top: 520, text: 'Email: piotr@kancelaria.pl', fontFamily: 'Georgia', fontSize: 18, fill: '#bdc3c7' },
      ],
    }),
  },
  {
    id: 'wiz-photo-1',
    name: 'Fotograf - Studio',
    productId: 'wiz-85x55',
    category: 'wizytowki',
    thumbnail: '/templates/wiz-photo-1.png',
    tags: ['fotograf', 'foto', 'kreatywny'],
    data: JSON.stringify({
      version: '5.3.0',
      objects: [
        { type: 'rect', left: 0, top: 0, width: 1004, height: 650, fill: '#2c2c2c' },
        { type: 'rect', left: 0, top: 0, width: 500, height: 650, fill: '#34495e', opacity: 0.5 },
        { type: 'text', left: 550, top: 150, text: 'FOTO', fontFamily: 'Arial', fontSize: 88, fill: '#ffffff', fontWeight: 'bold' },
        { type: 'text', left: 550, top: 250, text: 'STUDIO', fontFamily: 'Arial', fontSize: 68, fill: '#ecf0f1' },
        { type: 'text', left: 550, top: 380, text: 'Kamil Obiektyw', fontFamily: 'Arial', fontSize: 32, fill: '#f39c12' },
        { type: 'text', left: 550, top: 450, text: 'Fotograf Ślubny', fontFamily: 'Arial', fontSize: 22, fill: '#bdc3c7' },
        { type: 'text', left: 550, top: 520, text: '+48 123 456 789', fontFamily: 'Arial', fontSize: 18, fill: '#ecf0f1' },
        { type: 'text', left: 550, top: 550, text: 'foto@studio.pl', fontFamily: 'Arial', fontSize: 18, fill: '#ecf0f1' },
      ],
    }),
  },
  {
    id: 'wiz-beauty-1',
    name: 'Fryzjer - Salon Urody',
    productId: 'wiz-85x55',
    category: 'wizytowki',
    thumbnail: '/templates/wiz-beauty-1.png',
    tags: ['fryzjer', 'uroda', 'salon'],
    data: JSON.stringify({
      version: '5.3.0',
      objects: [
        { type: 'rect', left: 0, top: 0, width: 1004, height: 650, fill: '#fce4ec' },
        { type: 'rect', left: 800, top: 0, width: 204, height: 650, fill: '#e91e63' },
        { type: 'text', left: 60, top: 150, text: 'SALON URODY', fontFamily: 'Arial', fontSize: 48, fill: '#e91e63', fontWeight: 'bold' },
        { type: 'text', left: 60, top: 210, text: '"Metamorfoza"', fontFamily: 'Georgia', fontSize: 32, fill: '#880e4f' },
        { type: 'text', left: 60, top: 320, text: 'Katarzyna Piękna', fontFamily: 'Arial', fontSize: 28, fill: '#2c3e50' },
        { type: 'text', left: 60, top: 360, text: 'Stylistka & Fryzjer', fontFamily: 'Arial', fontSize: 20, fill: '#7f8c8d' },
        { type: 'text', left: 60, top: 480, text: 'Tel: +48 123 456 789', fontFamily: 'Arial', fontSize: 18, fill: '#c2185b' },
        { type: 'text', left: 60, top: 515, text: 'ul. Piękna 5, Warszawa', fontFamily: 'Arial', fontSize: 18, fill: '#c2185b' },
      ],
    }),
  },
  {
    id: 'wiz-chef-1',
    name: 'Chef - Restauracja',
    productId: 'wiz-85x55',
    category: 'wizytowki',
    thumbnail: '/templates/wiz-chef-1.png',
    tags: ['restauracja', 'gastronomia', 'kucharz'],
    data: JSON.stringify({
      version: '5.3.0',
      objects: [
        { type: 'rect', left: 0, top: 0, width: 1004, height: 650, fill: '#fff8e7' },
        { type: 'rect', left: 0, top: 0, width: 1004, height: 150, fill: '#c0392b' },
        { type: 'text', left: 60, top: 40, text: 'CHEF', fontFamily: 'Georgia', fontSize: 68, fill: '#ffffff', fontWeight: 'bold' },
        { type: 'text', left: 60, top: 250, text: 'Marek Smakosz', fontFamily: 'Georgia', fontSize: 42, fill: '#c0392b', fontWeight: 'bold' },
        { type: 'text', left: 60, top: 310, text: 'Szef Kuchni', fontFamily: 'Georgia', fontSize: 28, fill: '#7f8c8d' },
        { type: 'text', left: 60, top: 410, text: 'Restauracja "Smaki Świata"', fontFamily: 'Arial', fontSize: 22, fill: '#2c3e50' },
        { type: 'text', left: 60, top: 490, text: '+48 123 456 789  •  chef@smaki.pl', fontFamily: 'Arial', fontSize: 18, fill: '#7f8c8d' },
      ],
    }),
  },
  {
    id: 'wiz-fitness-1',
    name: 'Fitness - Trener Personalny',
    productId: 'wiz-85x55',
    category: 'wizytowki',
    thumbnail: '/templates/wiz-fitness-1.png',
    tags: ['fitness', 'trener', 'sport'],
    data: JSON.stringify({
      version: '5.3.0',
      objects: [
        { type: 'rect', left: 0, top: 0, width: 1004, height: 650, fill: '#1a1a1a' },
        { type: 'rect', left: 0, top: 550, width: 1004, height: 100, fill: '#e74c3c' },
        { type: 'text', left: 60, top: 100, text: 'PERSONAL', fontFamily: 'Arial', fontSize: 56, fill: '#e74c3c', fontWeight: 'bold' },
        { type: 'text', left: 60, top: 170, text: 'TRAINER', fontFamily: 'Arial', fontSize: 56, fill: '#ffffff', fontWeight: 'bold' },
        { type: 'text', left: 60, top: 300, text: 'Tomasz Silny', fontFamily: 'Arial', fontSize: 36, fill: '#ffffff' },
        { type: 'text', left: 60, top: 350, text: 'Certyfikowany Trener', fontFamily: 'Arial', fontSize: 22, fill: '#bdc3c7' },
        { type: 'text', left: 60, top: 575, text: '+48 123 456 789  •  trener@fitness.pl', fontFamily: 'Arial', fontSize: 18, fill: '#ffffff' },
      ],
    }),
  },
  {
    id: 'wiz-realestate-1',
    name: 'Nieruchomości - Agent',
    productId: 'wiz-85x55',
    category: 'wizytowki',
    thumbnail: '/templates/wiz-realestate-1.png',
    tags: ['nieruchomości', 'agent', 'dom'],
    data: JSON.stringify({
      version: '5.3.0',
      objects: [
        { type: 'rect', left: 0, top: 0, width: 1004, height: 650, fill: '#ffffff' },
        { type: 'rect', left: 0, top: 0, width: 350, height: 650, fill: '#3498db' },
        { type: 'text', left: 400, top: 120, text: 'NIERUCHOMOŚCI', fontFamily: 'Arial', fontSize: 38, fill: '#3498db', fontWeight: 'bold' },
        { type: 'text', left: 400, top: 230, text: 'Monika Dom', fontFamily: 'Arial', fontSize: 42, fill: '#2c3e50', fontWeight: 'bold' },
        { type: 'text', left: 400, top: 285, text: 'Doradca Nieruchomości', fontFamily: 'Arial', fontSize: 22, fill: '#7f8c8d' },
        { type: 'text', left: 400, top: 400, text: 'Tel: +48 123 456 789', fontFamily: 'Arial', fontSize: 20, fill: '#34495e' },
        { type: 'text', left: 400, top: 440, text: 'monika@domy.pl', fontFamily: 'Arial', fontSize: 20, fill: '#34495e' },
        { type: 'text', left: 400, top: 480, text: 'www.domy.pl', fontFamily: 'Arial', fontSize: 20, fill: '#3498db' },
      ],
    }),
  },
  {
    id: 'wiz-mechanic-1',
    name: 'Mechanik - Auto Serwis',
    productId: 'wiz-85x55',
    category: 'wizytowki',
    thumbnail: '/templates/wiz-mechanic-1.png',
    tags: ['mechanik', 'auto', 'serwis'],
    data: JSON.stringify({
      version: '5.3.0',
      objects: [
        { type: 'rect', left: 0, top: 0, width: 1004, height: 650, fill: '#2c2c2c' },
        { type: 'rect', left: 0, top: 0, width: 1004, height: 8, fill: '#f39c12' },
        { type: 'rect', left: 0, top: 642, width: 1004, height: 8, fill: '#f39c12' },
        { type: 'text', left: 60, top: 120, text: 'AUTO SERWIS', fontFamily: 'Arial', fontSize: 58, fill: '#f39c12', fontWeight: 'bold' },
        { type: 'text', left: 60, top: 200, text: 'Profesjonalna Naprawa', fontFamily: 'Arial', fontSize: 28, fill: '#ecf0f1' },
        { type: 'text', left: 60, top: 330, text: 'Robert Kluczyk', fontFamily: 'Arial', fontSize: 36, fill: '#ffffff' },
        { type: 'text', left: 60, top: 380, text: 'Mistrz Mechanik', fontFamily: 'Arial', fontSize: 22, fill: '#bdc3c7' },
        { type: 'text', left: 60, top: 500, text: '+48 123 456 789', fontFamily: 'Arial', fontSize: 20, fill: '#f39c12' },
        { type: 'text', left: 60, top: 535, text: 'ul. Warsztatowa 10, Warszawa', fontFamily: 'Arial', fontSize: 18, fill: '#ecf0f1' },
      ],
    }),
  },
  {
    id: 'wiz-construction-1',
    name: 'Budowlanka - Remonty',
    productId: 'wiz-85x55',
    category: 'wizytowki',
    thumbnail: '/templates/wiz-construction-1.png',
    tags: ['budowlanka', 'remonty', 'majster'],
    data: JSON.stringify({
      version: '5.3.0',
      objects: [
        { type: 'rect', left: 0, top: 0, width: 1004, height: 650, fill: '#f39c12' },
        { type: 'rect', left: 0, top: 0, width: 1004, height: 180, fill: '#2c3e50' },
        { type: 'text', left: 60, top: 50, text: 'REMONTY & BUDOWA', fontFamily: 'Arial', fontSize: 48, fill: '#f39c12', fontWeight: 'bold' },
        { type: 'text', left: 60, top: 280, text: 'Zbigniew Majster', fontFamily: 'Arial', fontSize: 46, fill: '#ffffff', fontWeight: 'bold' },
        { type: 'text', left: 60, top: 345, text: 'Kierownik Budowy', fontFamily: 'Arial', fontSize: 26, fill: '#2c3e50' },
        { type: 'text', left: 60, top: 470, text: 'Tel: +48 123 456 789', fontFamily: 'Arial', fontSize: 22, fill: '#2c3e50', fontWeight: 'bold' },
        { type: 'text', left: 60, top: 515, text: 'Doświadczenie 20 lat', fontFamily: 'Arial', fontSize: 20, fill: '#2c3e50' },
      ],
    }),
  },
  {
    id: 'wiz-florist-1',
    name: 'Kwiaciarnia - Florystyka',
    productId: 'wiz-85x55',
    category: 'wizytowki',
    thumbnail: '/templates/wiz-florist-1.png',
    tags: ['kwiaciarnia', 'kwiaty', 'florystyka'],
    data: JSON.stringify({
      version: '5.3.0',
      objects: [
        { type: 'rect', left: 0, top: 0, width: 1004, height: 650, fill: '#fff3e0' },
        { type: 'rect', left: 0, top: 0, width: 1004, height: 20, fill: '#e91e63' },
        { type: 'text', left: 502, top: 150, text: '🌸 KWIACIARNIA 🌸', fontFamily: 'Georgia', fontSize: 52, fill: '#e91e63', fontWeight: 'bold', textAlign: 'center' },
        { type: 'text', left: 502, top: 240, text: '"Róża"', fontFamily: 'Georgia', fontSize: 38, fill: '#c2185b', textAlign: 'center' },
        { type: 'text', left: 502, top: 350, text: 'Beata Kwiat', fontFamily: 'Arial', fontSize: 32, fill: '#2c3e50', textAlign: 'center' },
        { type: 'text', left: 502, top: 395, text: 'Florystka', fontFamily: 'Arial', fontSize: 22, fill: '#7f8c8d', textAlign: 'center' },
        { type: 'text', left: 502, top: 500, text: '+48 123 456 789', fontFamily: 'Arial', fontSize: 20, fill: '#e91e63', textAlign: 'center' },
        { type: 'text', left: 502, top: 540, text: 'ul. Kwiatowa 3, Warszawa', fontFamily: 'Arial', fontSize: 18, fill: '#7f8c8d', textAlign: 'center' },
      ],
    }),
  },
  {
    id: 'wiz-accounting-1',
    name: 'Księgowość - Biuro',
    productId: 'wiz-85x55',
    category: 'wizytowki',
    thumbnail: '/templates/wiz-accounting-1.png',
    tags: ['księgowość', 'finanse', 'podatki'],
    data: JSON.stringify({
      version: '5.3.0',
      objects: [
        { type: 'rect', left: 0, top: 0, width: 1004, height: 650, fill: '#ecf0f1' },
        { type: 'rect', left: 0, top: 0, width: 30, height: 650, fill: '#16a085' },
        { type: 'text', left: 80, top: 140, text: 'BIURO RACHUNKOWE', fontFamily: 'Arial', fontSize: 44, fill: '#16a085', fontWeight: 'bold' },
        { type: 'text', left: 80, top: 250, text: 'Elżbieta Liczby', fontFamily: 'Arial', fontSize: 38, fill: '#2c3e50', fontWeight: 'bold' },
        { type: 'text', left: 80, top: 305, text: 'Główna Księgowa', fontFamily: 'Arial', fontSize: 24, fill: '#7f8c8d' },
        { type: 'text', left: 80, top: 420, text: 'Księgowość • Podatki • ZUS', fontFamily: 'Arial', fontSize: 20, fill: '#16a085' },
        { type: 'text', left: 80, top: 490, text: 'Tel: +48 123 456 789', fontFamily: 'Arial', fontSize: 18, fill: '#34495e' },
        { type: 'text', left: 80, top: 525, text: 'ksiegowosc@biuro.pl', fontFamily: 'Arial', fontSize: 18, fill: '#34495e' },
      ],
    }),
  },
  {
    id: 'wiz-insurance-1',
    name: 'Ubezpieczenia - Doradca',
    productId: 'wiz-85x55',
    category: 'wizytowki',
    thumbnail: '/templates/wiz-insurance-1.png',
    tags: ['ubezpieczenia', 'doradca', 'finanse'],
    data: JSON.stringify({
      version: '5.3.0',
      objects: [
        { type: 'rect', left: 0, top: 0, width: 1004, height: 650, fill: '#2c3e50' },
        { type: 'rect', left: 700, top: 0, width: 304, height: 650, fill: '#3498db', opacity: 0.2 },
        { type: 'text', left: 60, top: 100, text: 'UBEZPIECZENIA', fontFamily: 'Arial', fontSize: 48, fill: '#3498db', fontWeight: 'bold' },
        { type: 'text', left: 60, top: 200, text: 'Paweł Bezpieczeństwo', fontFamily: 'Arial', fontSize: 36, fill: '#ffffff', fontWeight: 'bold' },
        { type: 'text', left: 60, top: 255, text: 'Doradca Ubezpieczeniowy', fontFamily: 'Arial', fontSize: 22, fill: '#ecf0f1' },
        { type: 'text', left: 60, top: 380, text: '✓ Auto  ✓ Dom  ✓ Życie', fontFamily: 'Arial', fontSize: 20, fill: '#3498db' },
        { type: 'text', left: 60, top: 480, text: '+48 123 456 789', fontFamily: 'Arial', fontSize: 20, fill: '#ecf0f1' },
        { type: 'text', left: 60, top: 520, text: 'pawel@ubezpieczenia.pl', fontFamily: 'Arial', fontSize: 20, fill: '#ecf0f1' },
      ],
    }),
  },
  {
    id: 'wiz-architect-1',
    name: 'Architekt - Studio',
    productId: 'wiz-85x55',
    category: 'wizytowki',
    thumbnail: '/templates/wiz-architect-1.png',
    tags: ['architekt', 'projektowanie', 'wnętrza'],
    data: JSON.stringify({
      version: '5.3.0',
      objects: [
        { type: 'rect', left: 0, top: 0, width: 1004, height: 650, fill: '#ffffff' },
        { type: 'rect', left: 0, top: 320, width: 1004, height: 4, fill: '#34495e' },
        { type: 'text', left: 502, top: 100, text: 'ARCH', fontFamily: 'Arial', fontSize: 88, fill: '#34495e', fontWeight: 'bold', textAlign: 'center' },
        { type: 'text', left: 502, top: 200, text: 'Studio Architektury', fontFamily: 'Arial', fontSize: 28, fill: '#7f8c8d', textAlign: 'center' },
        { type: 'text', left: 502, top: 380, text: 'Aleksandra Projekt', fontFamily: 'Arial', fontSize: 36, fill: '#2c3e50', textAlign: 'center' },
        { type: 'text', left: 502, top: 430, text: 'Architekt Wnętrz', fontFamily: 'Arial', fontSize: 22, fill: '#7f8c8d', textAlign: 'center' },
        { type: 'text', left: 502, top: 530, text: '+48 123 456 789  •  aleksandra@arch.pl', fontFamily: 'Arial', fontSize: 18, fill: '#34495e', textAlign: 'center' },
      ],
    }),
  },
  {
    id: 'wiz-handyman-1',
    name: 'Złota Rączka - Usługi',
    productId: 'wiz-85x55',
    category: 'wizytowki',
    thumbnail: '/templates/wiz-handyman-1.png',
    tags: ['złota-rączka', 'usługi', 'majster'],
    data: JSON.stringify({
      version: '5.3.0',
      objects: [
        { type: 'rect', left: 0, top: 0, width: 1004, height: 650, fill: '#f39c12' },
        { type: 'text', left: 502, top: 120, text: '🔧 ZŁOTA RĄCZKA 🔨', fontFamily: 'Arial', fontSize: 52, fill: '#2c3e50', fontWeight: 'bold', textAlign: 'center' },
        { type: 'text', left: 502, top: 250, text: 'Jan Majster', fontFamily: 'Arial', fontSize: 46, fill: '#ffffff', fontWeight: 'bold', textAlign: 'center' },
        { type: 'text', left: 502, top: 320, text: 'Wszelkie Naprawy i Usługi', fontFamily: 'Arial', fontSize: 24, fill: '#2c3e50', textAlign: 'center' },
        { type: 'text', left: 502, top: 430, text: 'Szybko • Solidnie • Tanio', fontFamily: 'Arial', fontSize: 22, fill: '#ffffff', textAlign: 'center' },
        { type: 'text', left: 502, top: 520, text: 'Tel: +48 123 456 789', fontFamily: 'Arial', fontSize: 26, fill: '#2c3e50', textAlign: 'center', fontWeight: 'bold' },
      ],
    }),
  },
];
