import { Template } from '@/types';

// Szablony ulotek
export const flyerTemplates: Template[] = [
  // PROMOCYJNE
  {
    id: 'ulotka-promo-1',
    name: 'Wyprzedaż - Rabat',
    productId: 'ulotka-a5',
    category: 'ulotki',
    thumbnail: '/templates/ulotka-promo-1.png',
    tags: ['promocja', 'wyprzedaż', 'rabat'],
    data: JSON.stringify({
      version: '5.3.0',
      objects: [
        { type: 'rect', left: 0, top: 0, width: 1748, height: 2480, fill: '#e74c3c' },
        { type: 'text', left: 874, top: 800, text: 'WIELKA WYPRZEDAŻ', fontFamily: 'Arial', fontSize: 96, fill: '#ffffff', fontWeight: 'bold', textAlign: 'center' },
        { type: 'text', left: 874, top: 1100, text: 'DO -50%', fontFamily: 'Arial', fontSize: 180, fill: '#ffffff', fontWeight: 'bold', textAlign: 'center' },
        { type: 'text', left: 874, top: 1400, text: 'NA WSZYSTKIE PRODUKTY', fontFamily: 'Arial', fontSize: 64, fill: '#ffffff', textAlign: 'center' },
        { type: 'text', left: 874, top: 1900, text: 'Tylko przez 7 dni!', fontFamily: 'Arial', fontSize: 48, fill: '#ffffff', textAlign: 'center' },
        { type: 'text', left: 874, top: 2100, text: 'www.sklep.pl  •  +48 123 456 789', fontFamily: 'Arial', fontSize: 32, fill: '#ffffff', textAlign: 'center' },
      ],
    }),
  },
  {
    id: 'ulotka-promo-2',
    name: 'Nowa Oferta',
    productId: 'ulotka-a4',
    category: 'ulotki',
    thumbnail: '/templates/ulotka-promo-2.png',
    tags: ['promocja', 'oferta', 'nowoczesny'],
    data: JSON.stringify({
      version: '5.3.0',
      objects: [
        { type: 'rect', left: 0, top: 0, width: 2480, height: 3508, fill: '#ffffff' },
        { type: 'rect', left: 0, top: 0, width: 2480, height: 600, fill: '#3498db' },
        { type: 'text', left: 1240, top: 200, text: 'NOWA OFERTA 2024', fontFamily: 'Arial', fontSize: 120, fill: '#ffffff', fontWeight: 'bold', textAlign: 'center' },
        { type: 'text', left: 1240, top: 350, text: 'Sprawdź nasze promocyjne ceny', fontFamily: 'Arial', fontSize: 52, fill: '#ffffff', textAlign: 'center' },
        { type: 'text', left: 200, top: 1000, text: '✓ Najwyższa jakość', fontFamily: 'Arial', fontSize: 72, fill: '#2c3e50' },
        { type: 'text', left: 200, top: 1200, text: '✓ Najlepsze ceny', fontFamily: 'Arial', fontSize: 72, fill: '#2c3e50' },
        { type: 'text', left: 200, top: 1400, text: '✓ Szybka realizacja', fontFamily: 'Arial', fontSize: 72, fill: '#2c3e50' },
        { type: 'text', left: 200, top: 1600, text: '✓ Darmowa dostawa', fontFamily: 'Arial', fontSize: 72, fill: '#2c3e50' },
        { type: 'rect', left: 0, top: 3200, width: 2480, height: 308, fill: '#3498db' },
        { type: 'text', left: 1240, top: 3320, text: 'Zadzwoń: +48 123 456 789  •  www.firma.pl', fontFamily: 'Arial', fontSize: 52, fill: '#ffffff', textAlign: 'center' },
      ],
    }),
  },
  {
    id: 'ulotka-promo-3',
    name: 'Restauracja - Menu',
    productId: 'ulotka-a5',
    category: 'ulotki',
    thumbnail: '/templates/ulotka-promo-3.png',
    tags: ['restauracja', 'menu', 'gastronomia'],
    data: JSON.stringify({
      version: '5.3.0',
      objects: [
        { type: 'rect', left: 0, top: 0, width: 1748, height: 2480, fill: '#fff8e7' },
        { type: 'text', left: 874, top: 150, text: 'MENU RESTAURACJI', fontFamily: 'Georgia', fontSize: 88, fill: '#c0392b', fontWeight: 'bold', textAlign: 'center' },
        { type: 'text', left: 874, top: 280, text: 'Tradycyjna Kuchnia Polska', fontFamily: 'Georgia', fontSize: 48, fill: '#7f8c8d', textAlign: 'center' },
        { type: 'rect', left: 100, top: 450, width: 1548, height: 3, fill: '#c0392b' },
        { type: 'text', left: 200, top: 600, text: '-20% NA WSZYSTKIE DANIA', fontFamily: 'Arial', fontSize: 64, fill: '#e74c3c', fontWeight: 'bold' },
        { type: 'text', left: 200, top: 800, text: 'Zimne przystawki od 15 zł', fontFamily: 'Arial', fontSize: 40, fill: '#2c3e50' },
        { type: 'text', left: 200, top: 880, text: 'Zupy domowe od 12 zł', fontFamily: 'Arial', fontSize: 40, fill: '#2c3e50' },
        { type: 'text', left: 200, top: 960, text: 'Dania główne od 25 zł', fontFamily: 'Arial', fontSize: 40, fill: '#2c3e50' },
        { type: 'text', left: 200, top: 1040, text: 'Desery od 10 zł', fontFamily: 'Arial', fontSize: 40, fill: '#2c3e50' },
        { type: 'rect', left: 100, top: 2100, width: 1548, height: 3, fill: '#c0392b' },
        { type: 'text', left: 874, top: 2250, text: 'Zapraszamy codziennie 12:00 - 22:00', fontFamily: 'Arial', fontSize: 44, fill: '#2c3e50', textAlign: 'center' },
        { type: 'text', left: 874, top: 2350, text: 'ul. Smaczna 1, Warszawa  •  Tel: +48 123 456 789', fontFamily: 'Arial', fontSize: 32, fill: '#7f8c8d', textAlign: 'center' },
      ],
    }),
  },

  // EVENTOWE
  {
    id: 'ulotka-event-1',
    name: 'Koncert - Festival',
    productId: 'ulotka-a4',
    category: 'ulotki',
    thumbnail: '/templates/ulotka-event-1.png',
    tags: ['event', 'koncert', 'festiwal'],
    data: JSON.stringify({
      version: '5.3.0',
      objects: [
        { type: 'rect', left: 0, top: 0, width: 2480, height: 3508, fill: '#2c3e50' },
        { type: 'text', left: 1240, top: 1200, text: 'WIELKI KONCERT', fontFamily: 'Arial', fontSize: 140, fill: '#f39c12', fontWeight: 'bold', textAlign: 'center' },
        { type: 'text', left: 1240, top: 1400, text: 'MUZYKA LIVE 2024', fontFamily: 'Arial', fontSize: 96, fill: '#ffffff', textAlign: 'center' },
        { type: 'rect', left: 400, top: 1700, width: 1680, height: 4, fill: '#f39c12' },
        { type: 'text', left: 1240, top: 1900, text: '15 Czerwca 2024  •  20:00', fontFamily: 'Arial', fontSize: 68, fill: '#ecf0f1', textAlign: 'center' },
        { type: 'text', left: 1240, top: 2050, text: 'Stadion Narodowy, Warszawa', fontFamily: 'Arial', fontSize: 64, fill: '#ecf0f1', textAlign: 'center' },
        { type: 'text', left: 1240, top: 2500, text: 'Bilety: www.bilety.pl', fontFamily: 'Arial', fontSize: 56, fill: '#f39c12', textAlign: 'center' },
      ],
    }),
  },
  {
    id: 'ulotka-event-2',
    name: 'Konferencja Biznesowa',
    productId: 'ulotka-a5',
    category: 'ulotki',
    thumbnail: '/templates/ulotka-event-2.png',
    tags: ['event', 'konferencja', 'biznes'],
    data: JSON.stringify({
      version: '5.3.0',
      objects: [
        { type: 'rect', left: 0, top: 0, width: 1748, height: 2480, fill: '#ecf0f1' },
        { type: 'rect', left: 0, top: 0, width: 1748, height: 500, fill: '#34495e' },
        { type: 'text', left: 874, top: 150, text: 'KONFERENCJA', fontFamily: 'Arial', fontSize: 88, fill: '#ffffff', fontWeight: 'bold', textAlign: 'center' },
        { type: 'text', left: 874, top: 260, text: 'Przyszłość Biznesu 2024', fontFamily: 'Arial', fontSize: 52, fill: '#3498db', textAlign: 'center' },
        { type: 'text', left: 200, top: 700, text: 'Data: 20-21 Marca 2024', fontFamily: 'Arial', fontSize: 48, fill: '#2c3e50', fontWeight: 'bold' },
        { type: 'text', left: 200, top: 800, text: 'Miejsce: Hotel Marriott, Warszawa', fontFamily: 'Arial', fontSize: 40, fill: '#7f8c8d' },
        { type: 'text', left: 200, top: 1000, text: 'Prelegenci:', fontFamily: 'Arial', fontSize: 44, fill: '#2c3e50', fontWeight: 'bold' },
        { type: 'text', left: 200, top: 1100, text: '• Jan Kowalski - CEO TechCorp', fontFamily: 'Arial', fontSize: 36, fill: '#34495e' },
        { type: 'text', left: 200, top: 1180, text: '• Anna Nowak - Ekspert AI', fontFamily: 'Arial', fontSize: 36, fill: '#34495e' },
        { type: 'text', left: 200, top: 1260, text: '• Piotr Wiśniewski - Strateg', fontFamily: 'Arial', fontSize: 36, fill: '#34495e' },
        { type: 'text', left: 874, top: 2200, text: 'Zarejestruj się: www.konferencja.pl', fontFamily: 'Arial', fontSize: 48, fill: '#3498db', textAlign: 'center', fontWeight: 'bold' },
      ],
    }),
  },
  {
    id: 'ulotka-event-3',
    name: 'Warsztaty - Szkolenie',
    productId: 'ulotka-a5',
    category: 'ulotki',
    thumbnail: '/templates/ulotka-event-3.png',
    tags: ['event', 'warsztaty', 'szkolenie'],
    data: JSON.stringify({
      version: '5.3.0',
      objects: [
        { type: 'rect', left: 0, top: 0, width: 1748, height: 2480, fill: '#ffffff' },
        { type: 'rect', left: 0, top: 0, width: 30, height: 2480, fill: '#27ae60' },
        { type: 'text', left: 150, top: 300, text: 'WARSZTATY', fontFamily: 'Arial', fontSize: 88, fill: '#27ae60', fontWeight: 'bold' },
        { type: 'text', left: 150, top: 420, text: 'Grafika Komputerowa', fontFamily: 'Arial', fontSize: 60, fill: '#2c3e50' },
        { type: 'text', left: 150, top: 700, text: 'Czego się nauczysz:', fontFamily: 'Arial', fontSize: 44, fill: '#2c3e50', fontWeight: 'bold' },
        { type: 'text', left: 150, top: 800, text: '✓ Adobe Photoshop - podstawy', fontFamily: 'Arial', fontSize: 36, fill: '#34495e' },
        { type: 'text', left: 150, top: 880, text: '✓ Adobe Illustrator - wektory', fontFamily: 'Arial', fontSize: 36, fill: '#34495e' },
        { type: 'text', left: 150, top: 960, text: '✓ Projektowanie logo', fontFamily: 'Arial', fontSize: 36, fill: '#34495e' },
        { type: 'text', left: 150, top: 1040, text: '✓ Przygotowanie do druku', fontFamily: 'Arial', fontSize: 36, fill: '#34495e' },
        { type: 'text', left: 150, top: 1300, text: 'Termin: 10-12 Lutego 2024', fontFamily: 'Arial', fontSize: 40, fill: '#7f8c8d' },
        { type: 'text', left: 150, top: 1380, text: 'Godziny: 10:00 - 16:00', fontFamily: 'Arial', fontSize: 40, fill: '#7f8c8d' },
        { type: 'text', left: 150, top: 1460, text: 'Cena: 499 zł (certyfikat w cenie)', fontFamily: 'Arial', fontSize: 40, fill: '#27ae60', fontWeight: 'bold' },
        { type: 'rect', left: 0, top: 2100, width: 1748, height: 380, fill: '#27ae60' },
        { type: 'text', left: 874, top: 2250, text: 'Zapisy: +48 123 456 789', fontFamily: 'Arial', fontSize: 48, fill: '#ffffff', textAlign: 'center', fontWeight: 'bold' },
      ],
    }),
  },

  // INFORMACYJNE
  {
    id: 'ulotka-info-1',
    name: 'Gabinet Lekarski',
    productId: 'ulotka-dl',
    category: 'ulotki',
    thumbnail: '/templates/ulotka-info-1.png',
    tags: ['informacyjny', 'medyczny', 'gabinet'],
    data: JSON.stringify({
      version: '5.3.0',
      objects: [
        { type: 'rect', left: 0, top: 0, width: 1169, height: 2480, fill: '#ffffff' },
        { type: 'rect', left: 0, top: 0, width: 1169, height: 20, fill: '#27ae60' },
        { type: 'text', left: 584, top: 150, text: 'PRZYCHODNIA', fontFamily: 'Arial', fontSize: 64, fill: '#27ae60', fontWeight: 'bold', textAlign: 'center' },
        { type: 'text', left: 584, top: 240, text: 'ZDROWIE', fontFamily: 'Arial', fontSize: 56, fill: '#2c3e50', textAlign: 'center' },
        { type: 'text', left: 100, top: 450, text: 'Godziny otwarcia:', fontFamily: 'Arial', fontSize: 40, fill: '#2c3e50', fontWeight: 'bold' },
        { type: 'text', left: 100, top: 530, text: 'Pon-Pt: 8:00 - 20:00', fontFamily: 'Arial', fontSize: 32, fill: '#7f8c8d' },
        { type: 'text', left: 100, top: 590, text: 'Sobota: 9:00 - 15:00', fontFamily: 'Arial', fontSize: 32, fill: '#7f8c8d' },
        { type: 'text', left: 100, top: 800, text: 'Usługi:', fontFamily: 'Arial', fontSize: 40, fill: '#2c3e50', fontWeight: 'bold' },
        { type: 'text', left: 100, top: 880, text: '• Medycyna rodzinna', fontFamily: 'Arial', fontSize: 28, fill: '#34495e' },
        { type: 'text', left: 100, top: 940, text: '• Pediatria', fontFamily: 'Arial', fontSize: 28, fill: '#34495e' },
        { type: 'text', left: 100, top: 1000, text: '• Ginekologia', fontFamily: 'Arial', fontSize: 28, fill: '#34495e' },
        { type: 'text', left: 100, top: 1060, text: '• Dermatologia', fontFamily: 'Arial', fontSize: 28, fill: '#34495e' },
        { type: 'rect', left: 0, top: 2100, width: 1169, height: 380, fill: '#27ae60' },
        { type: 'text', left: 584, top: 2220, text: 'Rejestracja:', fontFamily: 'Arial', fontSize: 36, fill: '#ffffff', textAlign: 'center' },
        { type: 'text', left: 584, top: 2300, text: '+48 123 456 789', fontFamily: 'Arial', fontSize: 44, fill: '#ffffff', textAlign: 'center', fontWeight: 'bold' },
      ],
    }),
  },
  {
    id: 'ulotka-info-2',
    name: 'Salon Fryzjerski',
    productId: 'ulotka-a6',
    category: 'ulotki',
    thumbnail: '/templates/ulotka-info-2.png',
    tags: ['informacyjny', 'salon', 'fryzjer'],
    data: JSON.stringify({
      version: '5.3.0',
      objects: [
        { type: 'rect', left: 0, top: 0, width: 1240, height: 1748, fill: '#fce4ec' },
        { type: 'text', left: 620, top: 150, text: 'SALON PIĘKNOŚCI', fontFamily: 'Arial', fontSize: 56, fill: '#e91e63', fontWeight: 'bold', textAlign: 'center' },
        { type: 'text', left: 620, top: 240, text: '"Metamorfoza"', fontFamily: 'Arial', fontSize: 40, fill: '#880e4f', textAlign: 'center' },
        { type: 'text', left: 100, top: 450, text: 'Cennik:', fontFamily: 'Arial', fontSize: 40, fill: '#880e4f', fontWeight: 'bold' },
        { type: 'text', left: 100, top: 540, text: 'Strzyżenie damskie: od 60 zł', fontFamily: 'Arial', fontSize: 28, fill: '#c2185b' },
        { type: 'text', left: 100, top: 600, text: 'Strzyżenie męskie: od 40 zł', fontFamily: 'Arial', fontSize: 28, fill: '#c2185b' },
        { type: 'text', left: 100, top: 660, text: 'Koloryzacja: od 120 zł', fontFamily: 'Arial', fontSize: 28, fill: '#c2185b' },
        { type: 'text', left: 100, top: 720, text: 'Ombre: od 200 zł', fontFamily: 'Arial', fontSize: 28, fill: '#c2185b' },
        { type: 'text', left: 100, top: 780, text: 'Trwała ondulacja: od 150 zł', fontFamily: 'Arial', fontSize: 28, fill: '#c2185b' },
        { type: 'rect', left: 0, top: 1400, width: 1240, height: 348, fill: '#e91e63' },
        { type: 'text', left: 620, top: 1500, text: 'Umów wizytę:', fontFamily: 'Arial', fontSize: 32, fill: '#ffffff', textAlign: 'center' },
        { type: 'text', left: 620, top: 1580, text: '+48 123 456 789', fontFamily: 'Arial', fontSize: 40, fill: '#ffffff', textAlign: 'center', fontWeight: 'bold' },
      ],
    }),
  },
];
