import { Template } from '@/types';

// Szablony plakatów, banerów i zaproszeń
export const posterBannerInviteTemplates: Template[] = [
  // PLAKATY
  {
    id: 'plakat-film-1',
    name: 'Plakat Filmowy - Thriller',
    productId: 'plakat-a2',
    category: 'plakaty',
    thumbnail: '/templates/plakat-film-1.png',
    tags: ['filmowy', 'kino', 'thriller'],
    data: JSON.stringify({
      version: '5.3.0',
      objects: [
        { type: 'rect', left: 0, top: 0, width: 4961, height: 7016, fill: '#000000' },
        { type: 'text', left: 2480, top: 5500, text: 'TYTUŁ FILMU', fontFamily: 'Arial', fontSize: 220, fill: '#ffffff', fontWeight: 'bold', textAlign: 'center' },
        { type: 'text', left: 2480, top: 5800, text: 'PREMIERA 2024', fontFamily: 'Arial', fontSize: 120, fill: '#e74c3c', textAlign: 'center' },
        { type: 'text', left: 2480, top: 6400, text: 'W KINACH OD 15 MARCA', fontFamily: 'Arial', fontSize: 88, fill: '#ecf0f1', textAlign: 'center' },
      ],
    }),
  },
  {
    id: 'plakat-event-1',
    name: 'Plakat Koncertowy',
    productId: 'plakat-a1',
    category: 'plakaty',
    thumbnail: '/templates/plakat-event-1.png',
    tags: ['koncert', 'muzyka', 'event'],
    data: JSON.stringify({
      version: '5.3.0',
      objects: [
        { type: 'rect', left: 0, top: 0, width: 7016, height: 9933, fill: '#8e44ad' },
        { type: 'rect', left: 0, top: 4500, width: 7016, height: 500, fill: '#ffffff', opacity: 0.2 },
        { type: 'text', left: 3508, top: 3500, text: 'SUMMER FEST', fontFamily: 'Arial', fontSize: 360, fill: '#ffffff', fontWeight: 'bold', textAlign: 'center' },
        { type: 'text', left: 3508, top: 4000, text: '2024', fontFamily: 'Arial', fontSize: 280, fill: '#f39c12', textAlign: 'center', fontWeight: 'bold' },
        { type: 'text', left: 3508, top: 5200, text: '15-16 CZERWCA', fontFamily: 'Arial', fontSize: 160, fill: '#ffffff', textAlign: 'center' },
        { type: 'text', left: 3508, top: 5500, text: 'PARK MIEJSKI', fontFamily: 'Arial', fontSize: 140, fill: '#ffffff', textAlign: 'center' },
        { type: 'text', left: 3508, top: 8500, text: 'BILETY: WWW.FEST.PL', fontFamily: 'Arial', fontSize: 120, fill: '#f39c12', textAlign: 'center', fontWeight: 'bold' },
      ],
    }),
  },
  {
    id: 'plakat-sport-1',
    name: 'Plakat Sportowy',
    productId: 'plakat-a3',
    category: 'plakaty',
    thumbnail: '/templates/plakat-sport-1.png',
    tags: ['sport', 'event', 'zawody'],
    data: JSON.stringify({
      version: '5.3.0',
      objects: [
        { type: 'rect', left: 0, top: 0, width: 3508, height: 4961, fill: '#ffffff' },
        { type: 'rect', left: 0, top: 0, width: 3508, height: 800, fill: '#e74c3c' },
        { type: 'rect', left: 0, top: 4161, width: 3508, height: 800, fill: '#e74c3c' },
        { type: 'text', left: 1754, top: 250, text: 'MARATON', fontFamily: 'Arial', fontSize: 180, fill: '#ffffff', fontWeight: 'bold', textAlign: 'center' },
        { type: 'text', left: 1754, top: 450, text: 'WARSZAWSKI 2024', fontFamily: 'Arial', fontSize: 100, fill: '#ffffff', textAlign: 'center' },
        { type: 'text', left: 1754, top: 2000, text: '21 KWIETNIA 2024', fontFamily: 'Arial', fontSize: 140, fill: '#2c3e50', textAlign: 'center', fontWeight: 'bold' },
        { type: 'text', left: 1754, top: 2250, text: 'Start: 9:00', fontFamily: 'Arial', fontSize: 100, fill: '#e74c3c', textAlign: 'center' },
        { type: 'text', left: 1754, top: 2900, text: 'DYSTANSE:', fontFamily: 'Arial', fontSize: 80, fill: '#2c3e50', textAlign: 'center', fontWeight: 'bold' },
        { type: 'text', left: 1754, top: 3100, text: '42km • 21km • 10km • 5km', fontFamily: 'Arial', fontSize: 88, fill: '#7f8c8d', textAlign: 'center' },
        { type: 'text', left: 1754, top: 4400, text: 'ZAPISY: WWW.MARATON.PL', fontFamily: 'Arial', fontSize: 88, fill: '#ffffff', textAlign: 'center', fontWeight: 'bold' },
      ],
    }),
  },

  // BANERY
  {
    id: 'baner-rollup-1',
    name: 'Roll-up Firmowy - Niebieski',
    productId: 'baner-100x200',
    category: 'banery',
    thumbnail: '/templates/baner-rollup-1.png',
    tags: ['firmowy', 'roll-up', 'biznes'],
    data: JSON.stringify({
      version: '5.3.0',
      objects: [
        { type: 'rect', left: 0, top: 0, width: 11811, height: 23622, fill: '#3498db' },
        { type: 'rect', left: 0, top: 10000, width: 11811, height: 3622, fill: '#2980b9' },
        { type: 'text', left: 5905, top: 8000, text: 'TWOJA FIRMA', fontFamily: 'Arial', fontSize: 480, fill: '#ffffff', fontWeight: 'bold', textAlign: 'center' },
        { type: 'text', left: 5905, top: 11000, text: 'Profesjonalne rozwiązania IT', fontFamily: 'Arial', fontSize: 280, fill: '#ffffff', textAlign: 'center' },
        { type: 'text', left: 5905, top: 16000, text: '✓ Najwyższa jakość', fontFamily: 'Arial', fontSize: 220, fill: '#ffffff', textAlign: 'center' },
        { type: 'text', left: 5905, top: 16600, text: '✓ Doświadczenie', fontFamily: 'Arial', fontSize: 220, fill: '#ffffff', textAlign: 'center' },
        { type: 'text', left: 5905, top: 17200, text: '✓ Konkurencyjne ceny', fontFamily: 'Arial', fontSize: 220, fill: '#ffffff', textAlign: 'center' },
        { type: 'text', left: 5905, top: 20000, text: 'www.firma.pl  •  +48 123 456 789', fontFamily: 'Arial', fontSize: 200, fill: '#ffffff', textAlign: 'center', fontWeight: 'bold' },
      ],
    }),
  },
  {
    id: 'baner-rollup-2',
    name: 'Roll-up Produktowy',
    productId: 'baner-100x200',
    category: 'banery',
    thumbnail: '/templates/baner-rollup-2.png',
    tags: ['produktowy', 'roll-up', 'oferta'],
    data: JSON.stringify({
      version: '5.3.0',
      objects: [
        { type: 'rect', left: 0, top: 0, width: 11811, height: 23622, fill: '#ffffff' },
        { type: 'rect', left: 0, top: 0, width: 11811, height: 3000, fill: '#27ae60' },
        { type: 'rect', left: 0, top: 20622, width: 11811, height: 3000, fill: '#27ae60' },
        { type: 'text', left: 5905, top: 800, text: 'NOWA OFERTA', fontFamily: 'Arial', fontSize: 420, fill: '#ffffff', fontWeight: 'bold', textAlign: 'center' },
        { type: 'text', left: 5905, top: 6000, text: 'PROMOCJA', fontFamily: 'Arial', fontSize: 520, fill: '#27ae60', fontWeight: 'bold', textAlign: 'center' },
        { type: 'text', left: 5905, top: 8000, text: '-30%', fontFamily: 'Arial', fontSize: 800, fill: '#e74c3c', fontWeight: 'bold', textAlign: 'center' },
        { type: 'text', left: 5905, top: 10500, text: 'NA WSZYSTKIE PRODUKTY', fontFamily: 'Arial', fontSize: 320, fill: '#2c3e50', textAlign: 'center' },
        { type: 'text', left: 5905, top: 15000, text: 'Tylko do końca miesiąca!', fontFamily: 'Arial', fontSize: 280, fill: '#7f8c8d', textAlign: 'center' },
        { type: 'text', left: 5905, top: 21500, text: 'WWW.SKLEP.PL', fontFamily: 'Arial', fontSize: 360, fill: '#ffffff', textAlign: 'center', fontWeight: 'bold' },
      ],
    }),
  },
  {
    id: 'baner-reklamowy-1',
    name: 'Baner Reklamowy - Restauracja',
    productId: 'baner-200x100',
    category: 'banery',
    thumbnail: '/templates/baner-reklamowy-1.png',
    tags: ['reklamowy', 'restauracja', 'gastronomia'],
    data: JSON.stringify({
      version: '5.3.0',
      objects: [
        { type: 'rect', left: 0, top: 0, width: 23622, height: 11811, fill: '#c0392b' },
        { type: 'text', left: 11811, top: 3500, text: 'RESTAURACJA "SMAK"', fontFamily: 'Georgia', fontSize: 520, fill: '#ffffff', fontWeight: 'bold', textAlign: 'center' },
        { type: 'text', left: 11811, top: 4500, text: 'Tradycyjna Kuchnia Polska', fontFamily: 'Georgia', fontSize: 320, fill: '#f39c12', textAlign: 'center' },
        { type: 'text', left: 11811, top: 7000, text: 'Otwarte codziennie 12:00 - 22:00', fontFamily: 'Arial', fontSize: 280, fill: '#ffffff', textAlign: 'center' },
        { type: 'text', left: 11811, top: 8000, text: 'ul. Smaczna 1  •  Tel: +48 123 456 789', fontFamily: 'Arial', fontSize: 240, fill: '#ffffff', textAlign: 'center' },
      ],
    }),
  },

  // ZAPROSZENIA
  {
    id: 'zapro-wesele-1',
    name: 'Zaproszenie Ślubne - Eleganckie',
    productId: 'zaproszenie-a5',
    category: 'zaproszenia',
    thumbnail: '/templates/zapro-wesele-1.png',
    tags: ['ślub', 'wesele', 'elegancki'],
    data: JSON.stringify({
      version: '5.3.0',
      objects: [
        { type: 'rect', left: 0, top: 0, width: 1748, height: 2480, fill: '#fdf6f0' },
        { type: 'rect', left: 200, top: 200, width: 1348, height: 2080, fill: 'transparent', stroke: '#d4af37', strokeWidth: 3 },
        { type: 'text', left: 874, top: 600, text: 'Serdecznie Zapraszamy', fontFamily: 'Georgia', fontSize: 64, fill: '#d4af37', textAlign: 'center' },
        { type: 'text', left: 874, top: 900, text: 'Anna & Piotr', fontFamily: 'Georgia', fontSize: 96, fill: '#5d4037', textAlign: 'center', fontWeight: 'bold' },
        { type: 'text', left: 874, top: 1200, text: 'Na Uroczystość Zaślubin', fontFamily: 'Georgia', fontSize: 48, fill: '#8d6e63', textAlign: 'center' },
        { type: 'text', left: 874, top: 1500, text: '15 Czerwca 2024', fontFamily: 'Georgia', fontSize: 56, fill: '#5d4037', textAlign: 'center', fontWeight: 'bold' },
        { type: 'text', left: 874, top: 1600, text: 'godz. 15:00', fontFamily: 'Georgia', fontSize: 44, fill: '#8d6e63', textAlign: 'center' },
        { type: 'text', left: 874, top: 1900, text: 'Kościół św. Anny', fontFamily: 'Georgia', fontSize: 40, fill: '#8d6e63', textAlign: 'center' },
        { type: 'text', left: 874, top: 1980, text: 'ul. Kwiatowa 10, Warszawa', fontFamily: 'Georgia', fontSize: 36, fill: '#8d6e63', textAlign: 'center' },
      ],
    }),
  },
  {
    id: 'zapro-urodziny-1',
    name: 'Zaproszenie Urodzinowe - Kolorowe',
    productId: 'zaproszenie-square',
    category: 'zaproszenia',
    thumbnail: '/templates/zapro-urodziny-1.png',
    tags: ['urodziny', 'impreza', 'kolorowy'],
    data: JSON.stringify({
      version: '5.3.0',
      objects: [
        { type: 'rect', left: 0, top: 0, width: 1772, height: 1772, fill: '#fff3e0' },
        { type: 'circle', left: 200, top: 200, radius: 150, fill: '#e74c3c', opacity: 0.3 },
        { type: 'circle', left: 1200, top: 1200, radius: 180, fill: '#3498db', opacity: 0.3 },
        { type: 'circle', left: 1300, top: 300, radius: 120, fill: '#f39c12', opacity: 0.3 },
        { type: 'text', left: 886, top: 400, text: 'ZAPROSZENIE', fontFamily: 'Arial', fontSize: 72, fill: '#e74c3c', textAlign: 'center', fontWeight: 'bold' },
        { type: 'text', left: 886, top: 550, text: 'na 30-te urodziny', fontFamily: 'Arial', fontSize: 56, fill: '#2c3e50', textAlign: 'center' },
        { type: 'text', left: 886, top: 750, text: 'JULII', fontFamily: 'Arial', fontSize: 88, fill: '#e74c3c', textAlign: 'center', fontWeight: 'bold' },
        { type: 'text', left: 886, top: 950, text: '20 Marca 2024, godz. 19:00', fontFamily: 'Arial', fontSize: 44, fill: '#34495e', textAlign: 'center' },
        { type: 'text', left: 886, top: 1100, text: 'Restauracja "Pod Gwiazdami"', fontFamily: 'Arial', fontSize: 40, fill: '#34495e', textAlign: 'center' },
        { type: 'text', left: 886, top: 1500, text: 'Potwierdzenie obecności:', fontFamily: 'Arial', fontSize: 32, fill: '#7f8c8d', textAlign: 'center' },
        { type: 'text', left: 886, top: 1560, text: '+48 123 456 789', fontFamily: 'Arial', fontSize: 36, fill: '#3498db', textAlign: 'center', fontWeight: 'bold' },
      ],
    }),
  },
  {
    id: 'zapro-biznes-1',
    name: 'Zaproszenie Biznesowe',
    productId: 'zaproszenie-a5',
    category: 'zaproszenia',
    thumbnail: '/templates/zapro-biznes-1.png',
    tags: ['biznes', 'event', 'formalny'],
    data: JSON.stringify({
      version: '5.3.0',
      objects: [
        { type: 'rect', left: 0, top: 0, width: 1748, height: 2480, fill: '#ffffff' },
        { type: 'rect', left: 0, top: 0, width: 1748, height: 400, fill: '#2c3e50' },
        { type: 'text', left: 874, top: 120, text: 'ZAPROSZENIE', fontFamily: 'Arial', fontSize: 88, fill: '#ffffff', fontWeight: 'bold', textAlign: 'center' },
        { type: 'text', left: 874, top: 700, text: 'Mamy zaszczyt zaprosić', fontFamily: 'Georgia', fontSize: 52, fill: '#2c3e50', textAlign: 'center' },
        { type: 'text', left: 874, top: 900, text: 'na uroczystą galę', fontFamily: 'Georgia', fontSize: 64, fill: '#2c3e50', textAlign: 'center', fontWeight: 'bold' },
        { type: 'text', left: 874, top: 1100, text: 'z okazji 20-lecia Firmy', fontFamily: 'Georgia', fontSize: 52, fill: '#3498db', textAlign: 'center' },
        { type: 'text', left: 874, top: 1400, text: '25 Maja 2024', fontFamily: 'Arial', fontSize: 56, fill: '#2c3e50', textAlign: 'center', fontWeight: 'bold' },
        { type: 'text', left: 874, top: 1500, text: 'godz. 18:00', fontFamily: 'Arial', fontSize: 48, fill: '#7f8c8d', textAlign: 'center' },
        { type: 'text', left: 874, top: 1750, text: 'Hotel Marriott', fontFamily: 'Arial', fontSize: 48, fill: '#34495e', textAlign: 'center' },
        { type: 'text', left: 874, top: 1840, text: 'Al. Jerozolimskie 65/79, Warszawa', fontFamily: 'Arial', fontSize: 40, fill: '#7f8c8d', textAlign: 'center' },
        { type: 'rect', left: 0, top: 2200, width: 1748, height: 280, fill: '#ecf0f1' },
        { type: 'text', left: 874, top: 2300, text: 'Potwierdzenie do 10 Maja: rsvp@firma.pl', fontFamily: 'Arial', fontSize: 36, fill: '#2c3e50', textAlign: 'center' },
      ],
    }),
  },
];
